package org.apache.hadoop.yarn.applications.narwhal.config;

/**
 * Created by zyluo on 6/7/16.
 */
public class NarwhalConfigCorpus {
    public final static String readmeInput = new StringBuilder()
            .append("{\n")
            .append("  'name': 'hello-docker',\n")
            .append("  'cpus': 2.0,\n")
            .append("  'mem': 32.0,\n")
            .append("  'instances': 2,\n")
            .append("  'cmd': 'echo \\\"hello docker\\\"',\n")
            .append("  'engine': {\n")
            .append("    'type': 'DOCKER',\n")
            .append("    'image': 'centos',\n")
            .append("    'localImage': true\n")
            .append("  }\n")
            .append("}")
            .toString();

    public final static String readmeOutput = new StringBuilder()
            .append("name: hello-docker\n")
            .append("cpus: 2.0\n")
            .append("mem: 32.0\n")
            .append("instances: 2\n")
            .append("cmd: echo \"hello docker\"\n")
            .append("engine_type: DOCKER\n")
            .append("engine_image: centos\n")
            .append("engine_localImage: true\n")
            .toString();

    public final static String testVolumeMountInput = new StringBuilder()
            .append("{\n")
            .append("  'name': 'hello-docker',\n")
            .append("  'cpus': 2.0,\n")
            .append("  'mem': 32.0,\n")
            .append("  'instances': 2,\n")
            .append("  'cmd': 'echo \\\"hello docker\\\"',\n")
            .append("  'engine': {\n")
            .append("    'type': 'DOCKER',\n")
            .append("    'image': 'centos',\n")
            .append("    'localImage': true,\n")
            .append("    'volumes': [\n")
            .append("      {\n")
            .append("        'containerPath': '/etc/a',\n")
            .append("        'hostPath': '/var/a',\n")
            .append("        'mode': 'RO'\n")
            .append("      },\n")
            .append("      {\n")
            .append("        'containerPath': '/etc/b',\n")
            .append("        'hostPath': '/var/b',\n")
            .append("        'mode': 'RO'\n")
            .append("      }\n")
            .append("    ]\n")
            .append("  }\n")
            .append("}")
            .toString();

    public final static String testVolumeMountOutput = new StringBuilder()
            .append("name: hello-docker\n")
            .append("cpus: 2.0\n")
            .append("mem: 32.0\n")
            .append("instances: 2\n")
            .append("cmd: echo \"hello docker\"\n")
            .append("engine_type: DOCKER\n")
            .append("engine_image: centos\n")
            .append("engine_localImage: true\n")
            .append("engine_volume_containerPath: /etc/a\n")
            .append("engine_volume_hostPath: /var/a\n")
            .append("engine_volume_mountMode: RO\n")
            .append("engine_volume_containerPath: /etc/b\n")
            .append("engine_volume_hostPath: /var/b\n")
            .append("engine_volume_mountMode: RO\n")
            .toString();
}
